### ISSUE TITLE
A thread of thanks

### ISSUE THREAD

**Issue by 2ndMessiah** [PaPerseller/chn-iplist#11]
This is probably the only v2rayNG compatible rules.

To v2rayNG users: Be sure to enable local DNS while using custom rules, or some of the parsed IP returned by the public DNS would be misclassified by the app( which I think of as actually a bug), and this is also what the official dev's recommendation.

Keep up your good work man.

Appreciate it.

ps: Op could close this issue directly seeing it.

**Comment by PaPerseller** [comment]
Thank you for your approval of my project.
