### ISSUE TITLE
Commas missing in V2RayNG 'proxy' config?

### ISSUE THREAD

**Issue by 2ndMessiah** [PaPerseller/chn-iplist#12]
> 91.108.4.0/22
> 91.108.56.0/22
> 91.108.56.0/23
> 91.108.56.0/24
> 91.108.8.0/22
> 109.239.140.0/24
> 149.154.160.0/20
> 149.154.160.0/22
> 149.154.164.0/22
> 149.154.168.0/22
> 149.154.172.0/22
> 149.154.167.0/24
> 149.154.175.0/24
> 2001:67c:4e8::/48
> 2001:b28:f23d::/48
> 2001:b28:f23f::/48

Plz validate them.

**Comment by PaPerseller** [comment]
Thanks for your comment. There are also some other issues. But these days I am busy with work and have no time to touch my computer. Please wait for me a few days to fix them.

**Comment by PaPerseller** [comment]
Fixed.
