### ISSUE TITLE
v2ray 内嵌规则 文本格式错误

### ISSUE THREAD

**Issue by ThomasZN** [PaPerseller/chn-iplist#13]
[v2ray规则文本](https://raw.githubusercontent.com/PaPerseller/chn-iplist/master/v2ray-config_rule.txt)有json格式错误。

拷贝到[JSONLint](https://jsonlint.com/)中，删掉前缀 `"routing" :` 和 后缀 `,` ，检查可得到若干行错误，如 line 93:

```
92		"domain:softpedia.com",
93		"domain:mtalk.google.com"
94		"domain:ip6-localhost",
```

**Comment by PaPerseller** [comment]
已修复
