### ISSUE TITLE
Shadowrocket.conf URL rewrite

### ISSUE THREAD

**Issue by rivermud** [PaPerseller/chn-iplist#14]
首先感谢朋友您做出了这么好的规则，我用了很久了，非常方便。非常感谢。

提一个小小的问题，您的 Shaowrocket 规则中 g,cn 和 google.cn 的 URL 重写类型选择的是 HEADER，这个类型现在在 iOS 上无法生效了，我每次更新后都得手动调整为 302。

不知您看看是否方便的时候调整一下？

**Comment by PaPerseller** [comment]
已在[e7d596c
](https://github.com/PaPerseller/chn-iplist/commit/e7d596ca4b6bb44bc1474fa10bd59d447502433d)中进行了修改，请尝试下是否可用
