### ISSUE TITLE
Shouldn't geosute be geosite?

### ISSUE THREAD

**Issue by C-Entropy** [PaPerseller/chn-iplist#15]
[here](https://github.com/PaPerseller/chn-iplist/blob/0f1d38b44b7e88770b77bb46638838053d9634e3/v2rayN(G)/proxy.txt#L6), shouldn't geosute be geosite?

**Comment by PaPerseller** [comment]
Fixed it. Please update. Thank you.

**Comment by C-Entropy** [comment]
Thank you!
