### ISSUE TITLE
中国电信网络环境下 App Store ”正在载入“

### ISSUE THREAD

**Issue by rivermud** [PaPerseller/chn-iplist#17]
https://github.com/PaPerseller/chn-iplist/blob/master/Shadowrocket.conf
Shadowrocket 配置
中国电信网络环境下 App Store  ”正在载入“，关闭 Shadowrocket 连接无此问题，使用其他配置文件无此问题。
中国移动网络环境下无此问题。
具体我也没仔细查，暂时提供不了更多的信息了。

**Comment by PaPerseller** [comment]
本人是美区账号，在电信宽带网络下测试正常。制作了一份去除apple直连规则的版本，请试用
[Shadowrocket-test.txt](https://github.com/PaPerseller/chn-iplist/files/6778036/Shadowrocket-test.txt)
