### ISSUE TITLE
请问Shadowrocket的规则能不能指点一下

### ISSUE THREAD

**Issue by 760644586** [PaPerseller/chn-iplist#18]
1.
URL-REGEX,*.baidu.com\/*.jpg,Reject-200
URL-REGEX,*.baidu.com\/*.png,Reject-200
URL-REGEX,*.baidu.com\/*.bmp,Reject-200
URL-REGEX,*.baidu.com\/*.mp4,Reject-200
URL-REGEX,*.baidu.com\/*.svg,Reject-200
URL-REGEX,*.baidu.com\/*.jpeg,Reject-200

2.
URL-REGEX,*.baidu.com/*.jpg,Reject-200
URL-REGEX,*.baidu.com/*.png,Reject-200
URL-REGEX,*.baidu.com/*.bmp,Reject-200
URL-REGEX,*.baidu.com/*.mp4,Reject-200
URL-REGEX,*.baidu.com/*.svg,Reject-200
URL-REGEX,*.baidu.com/*.jpeg,Reject-200

我想用上面的代码,拦截图片类连接,但是发现无效.上面两种方法我都测试过了.

**Comment by PaPerseller** [comment]
你好，本人不会此类语法，请再自行研究试试。
