### ISSUE TITLE
反馈一个关于 MITM 的问题

### ISSUE THREAD

**Issue by RiverMud** [PaPerseller/chn-iplist#21]
iOS15，打开 HTTPS 解密，使用 Safari 时，地区大陆，默认搜索引擎 google.cn 无法跳转为 https://www.google.com，把中间人解密里的域名改成 www.google.cn 即可，但更新后就变回来默认的*.google.cn和*.google.com.hk 然后就又失效了。

不知道我这个问题是不是特有的，烦请大佬看下。

**Comment by rivermud** [comment]
说错了，https解密里是google.com.cn，没有google.cn的字段，iOS下Safari默认引擎无法生效。Shadowrocket

**Comment by PaPerseller** [comment]
已合并您的提交。我这边自 ios16.4beta 开始某些版本中间人解密填 *.google.cn 后跳转会失效，所以作了修改。目前测试 *.google.cn 正常且可移除 *.google.com.cn
