### ISSUE TITLE
填写方式

### ISSUE THREAD

**Issue by GD2021** [PaPerseller/chn-iplist#27]
![image](https://github.com/PaPerseller/chn-iplist/assets/81171294/2e4cadfa-6f3a-42ea-93f8-6f8c9cf1acd3)
请问我这样粘贴是否正确呢？

**Comment by PaPerseller** [comment]
本人不知 v2rayN 已将域名和 ip 分开填写。现已更新 v2rayN 规则将每种类型中域名和 ip 分为上下顺序，便于v2rayN 中分离使用
