### ISSUE TITLE
用了v2rayA.txt规则后，微信扫码无法登录

### ISSUE THREAD

**Issue by ymcoming** [PaPerseller/chn-iplist#28]
环境：局域网下一台PC和一部手机均通过路由器的v2rayA透明代理上网，使用的分流策略为v2rayA.txt

原因：想通过微信文件传输助手完成电脑和手机的文件交换，PC浏览器打开：https://szfilehelper.weixin.qq.com/，出现登陆码认证。正常情况下，手机打开微信扫码即可让PC登陆。

但手机扫码后无法跳转至认证网页，导致无法认证通过。而关掉手机wifi用5G数据流量后，扫码则有一个正常跳转，来到认证确认页面，点确认后PC即可登陆成功。

**Comment by PaPerseller** [comment]
我这边同样用网页版试了下，可以正常登陆，未复现。请尝试将 block 规则中 `, geosite:category-httpdns` 删除或者注释掉 `domain(geosite:category-ads-all, geosite:category-httpdns) -> block` ，若问题仍存在，则我猜测可能与环境中 dns 设置有关

**Comment by ymcoming** [comment]
谢谢，我把geosite:category-httpdns删掉就正常了。

**Comment by PaPerseller** [comment]
> 谢谢，我把geosite:category-httpdns删掉就正常了。

感谢反馈，我会将这条规则默认注释掉
