### ISSUE TITLE
Kitsunebi (iOS) 需要 base64 加密后的内容

### ISSUE THREAD

**Issue by zzc-tongji** [PaPerseller/chn-iplist#3]
能否同时提供加密后的版本？

**Comment by PaPerseller** [comment]
请问您的kit版本号是多少，您的版本和我自己创建的版本在 6s kit2.3.5(175) 下好像不可用

**Comment by zzc-tongji** [comment]
![IMG_01733B5BFB35-1](https://user-images.githubusercontent.com/20331014/60406183-3c202100-9be7-11e9-84fb-698dc2a9a618.jpeg)

**Comment by PaPerseller** [comment]
请问能试下我上传的版本吗？看看能不能用

**Comment by zzc-tongji** [comment]
你的版本不能用。

kitsunebi 内置的版本是这个：

https://raw.githubusercontent.com/eycorsican/rule-sets/master/kitsunebi_sub

貌似是 base64 但是没有换行，去问问原作者吧。

**Comment by PaPerseller** [comment]
我会再研究尝试下
