### ISSUE TITLE
Clash config file error

### ISSUE THREAD

**Issue by nyaachen** [PaPerseller/chn-iplist#5]
file clash/clash.yml line 57 

>  \- IP-CIDR,91.108.56.116,PROXY

this is invalid in Clash rule file

**Comment by PaPerseller** [comment]
fixed, please try new version. [clash.yml](https://github.com/PaPerseller/chn-iplist/blob/master/clash/clash.yml )

**Comment by nyaachen** [comment]
Thank you for fixing it.
