### ISSUE TITLE
v2ray内嵌规则中的正则转义符引发报错

### ISSUE THREAD

**Issue by UudrSgMEZ** [PaPerseller/chn-iplist#6]
[v2ray 配置内嵌规则](https://raw.githubusercontent.com/PaPerseller/chn-iplist/master/v2ray-config_rule.txt)里面的正则表达式和[v2ray.com/routing](https://v2ray.com/chapter_02/03_routing.html)里面的正则表达式的转义符使用方式好像有点不一样，把这些正则表达式直接复制到config.json里面之后v2ray-core报错：
`failed to parse json config`。

chn-iplist中的正则：
`"regexp:^https?:\/\/.+\.googlevideo\.com\/.+&oad"`

v2ray.com中的正则：
`"regexp:\\.goo.*\\.com$"`

**Comment by PaPerseller** [comment]
确认是正则格式有问题，但我不懂这个，请问你能提交pull request吗？

**Comment by UudrSgMEZ** [comment]
翻了一下项目，没找到生成这些正则的代码。
如果手工改以后每次更新又要维护一次，同时这些正则也不是很重要。
所以可以考虑下直接删除那些正则。
（其实真正的原因是我比较懒）

**Comment by PaPerseller** [comment]
正则中很多确实和前面的许多关键词是重合的，会将其直接删除
