### ISSUE TITLE
请问v2rayNg,怎么将apple加入白名单，apple music卡

### ISSUE THREAD

**Issue by shellwolrd** [PaPerseller/chn-iplist#8]

**Comment by PaPerseller** [comment]
本规则以国内ip为白名单，请问你是想将apple相关放入直连还是代理？若想直连apple，可将apple music放入绕行应用中，或者我在下期更新中加入apple直连规则；若想走代理，经测试现有规则下，流媒体播放时已是走的代理。

**Comment by PaPerseller** [comment]
临时解决办法：在直连中加入以下规则
domain:apple.com,
domain:crashlytics.com,
domain:icloud.com,
domain:itunes.com,
domain:push-apple.com.akadns.net,
domain:aaplimg.com,
domain:me.com,
domain:mzstatic.com,
domain:api.smoot.apple.com.cn,
domain:captive.apple.com,
domain:cn-smp-paymentservices.apple.com,
domain:smp-device.apple.com,
domain:smp-device-content.apple.com,
domain:sp.itunes.apple.com,
domain:ess.apple.com,
domain:push.apple.com,
domain:gs-loc.apple.com,
domain:ls.apple.com,

**Comment by shellwolrd** [comment]
感谢！我是想将apple Music加入直连当中。

**Comment by PaPerseller** [comment]
> 感谢！我是想将apple Music加入直连当中。

那先手动添加上面给的规则吧，经测试有效。将在下次更新中加入。
