### ISSUE TITLE
clash for android(1.1.10)规则格式问题

### ISSUE THREAD

**Issue by MofaZhuzai** [PaPerseller/chn-iplist#9]
- IP-CIDR,61.132.98.242,DIRECT 在clash for Android(1.1.10)显示payload error，
建议改成- IP-CIDR,61.132.98.242/32,DIRECT

**Comment by PaPerseller** [comment]
61.132.98.242 本身不是cidr格式，是类型错误不是格式错误，同时此ip为本人工作用地址，所以已将其从所有规则中删除，请进行更新

**Comment by PaPerseller** [comment]
同时为 clash for android 制作的 clash 策略规则已上传，可使用 subconverter 或其他衍生工具导入使用。
